# supabase/config.template.toml

[auth]
enabled = true

# fill this in via Makefile (dev vs prod)
site_url = "{{SITE_URL}}"

additional_redirect_urls = [
  "{{SITE_URL}}/auth/v1/callback",
  "{{SITE_URL}}/auth/callback",
]

jwt_expiry                    = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval  = 10