# netlify.toml

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/budget/*"
  to = "/budget/index.html"
  status = 200

[[redirects]]
  from = "/budget"
  to = "/budget/dashboard"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200