# old/config.toml

[auth]
enabled = true

# fill this in via Makefile (dev vs prod)
site_url = ""

additional_redirect_urls = [
  "/auth/v1/callback",
  "/auth/callback",
]

jwt_expiry                    = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval  = 10